name: Deploy Server to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
      - "packages/**"
      - ".github/workflows/deploy.yml"
      - "alchemy.run.ts"

concurrency:
  group: "publish"
  cancel-in-progress: false

jobs:
  deploy:
    environment: "production"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check types
        run: bun run check-types

      - name: Get DB Cert File
        run: curl --create-dirs -o $HOME/.postgresql/root.crt '${{ env.PAGEDECK_DATABASE_CERT_URL }}'
        env:
          PAGEDECK_DATABASE_CERT_URL: ${{ secrets.PAGEDECK_DATABASE_CERT_URL }}

      - name: Database Migration
        run: bun run db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production
        working-directory: ./packages/pagedeck/db

      - name: Deploy Application
        run: |
          bun run deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          PAGEDECK_BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          PAGEDECK_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PAGEDECK_POLAR_ACCESS_TOKEN: ${{ secrets.POLAR_ACCESS_TOKEN }}
          ALCHEMY_PASSWORD: ${{ secrets.ALCHEMY_PASSWORD }}
          ALCHEMY_STATE_STORE: cloudflare
          ALCHEMY_STATE_TOKEN: ${{ secrets.ALCHEMY_STATE_TOKEN }}
          PAGEDECK_BETTER_AUTH_URL: ${{ vars.BETTER_AUTH_URL }}
          PAGEDECK_CORS_ORIGIN: ${{ vars.CORS_ORIGIN }}
          NODE_ENV: production
          PAGEDECK_POLAR_SUCCESS_URL: ${{ vars.POLAR_SUCCESS_URL }}
          PAGEDECK_VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
          STAGE: prod
